
service: appsync-ts-crud

frameworkVersion: '2'

plugins:
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

package:
  exclude: 
    - package-lock.json
    - package.json
  individually: true

custom:
  appSync:
    - ${file(serverless.appsync-api.yml)}

